### PR TITLE
Fix TypeExpression "JIT stack limit exhausted"

### PR DESCRIPTION
**Pull request by mvorisek**
for/into #7843

I fixed all places

and removed the test as there is `testHugeType` - feel free to add some (originally) failing type if the test from #7841 is not enough

### CODE REVIEW

**Review by kubawerlos — CHANGES_REQUESTED** [review]
Please restore these removed tests, they were added in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7843 to cover `+` added in line 62 (and it is visible in commits that they do that). Test `testHugeType` is not related to what we are fixing here, as it is already passing on the main branch.

Also, since when have we started adding changes to `src` without covering them with tests? I consider the pluses added in lines 81 and 98 not as fixes, but as random changes, as there is no proof they fix anything.

**Comment by mvorisek** [comment]
@kubawerlos please look at https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7843#discussion_r1493521309, `.+` is stricter (faster), thus if tests pass, the changes are covered.

about the test - `testHugeType` is not different and I have crafted it for exactly there purposes, the "JIT stack limit exhausted" was not detected by it as the PHPDoc is passing, but feel free to modify that test to produce also large "almost valid" PHPDocs.

**Comment by kubawerlos** [comment]
> feel free to modify that test to produce also large "almost valid" PHPDocs.

I was thinking about converting `testHugeType` to be just a case in `testGetTypes` and `testParseInvalidException` (with removing of last character (or few last characters).

Also, for changes in `src` I still insist we need to have a tests that cover them, as without them one day someone can remove them and nothing will happen.

**Comment by mvorisek** [comment]
I would probably keep `testHugeType` as a separate test/tests, as debugging other tests with huge strings is not the easiest, also, the `testHugeType` takes quite a lot of time, basically it is on the edge what pcre can handle.

Currently, `testHugeType` tests long union and deeply nested/recursive parsing.

The test you added is testing long array shape. Yes, it should be tested, I have reverted the revert and renamed it to stress this.

**Comment by Wirone** [comment]
@mvorisek can you resolve conflicts? I can approve the workflow then.

**Comment by mvorisek** [comment]
@Wirone conflict fixed

**Comment by kubawerlos** [comment]
Merging, so you can push changes to other PR and (hopefully) it will trigger CI right away.

**Pull request merged**
